---
# check if Java is already installed for impotence

- name: check if tomcat is installed
  stat:
    path: "{{ tomcat_install_folder }}/bin/startup.sh"
  register: isInstalled
  ignore_errors: true
  changed_when: false
  failed_when: false

- name: installing tomcat
  block:

    # tasks file for tomcat
    - name: "Create user for tomcat: {{ tomcat_user }}"
      user:
        name: "{{ tomcat_user }}"
        shell: /bin/bash

    # create directory for tomcat
    - name: "Create tomcat directory {{ tomcat_install_folder }}"
      file:
        path: "{{ tomcat_install_folder }}"
        state: directory

    # Download Tomcat from source
    - name: Download Tomcat 8.5.34
      get_url:
        url: https://repo.maven.apache.org/maven2/org/apache/tomcat/tomcat/8.5.34/tomcat-8.5.34.tar.gz
        dest: "{{ tomcat_install_folder }}"

    - name: unzip tomcat binary
      unarchive:
        src: "{{ tomcat_install_folder }}/tomcat-8.5.34.tar.gz"
        dest: "{{ tomcat_install_folder }}"
        copy: false
        extra_opts: "--strip-components=1"

    - name: change ownership on {{ tomcat_install_folder }} to {{ tomcat_user }}
      file:
        path: "{{ tomcat_install_folder }}"
        state: directory
        mode: 0755
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_user }}"
        recurse: true

    ## clean up

    - name: Clear up downloaded tomcat download
      file:
        path: "{{ tomcat_install_folder }}/tomcat-8.5.34.tar.gz"
        state: absent
  when: not isInstalled.stat.exists
